version: "3.8"

services:
  # The main web application service
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    volumes:
      # Mount the current directory into the container for live-reloading
      - .:/app
    env_file:
      - .env
    ports:
      # Expose the application port to the host machine
      - "3000:3000"
    # Run the async FastAPI server via uvicorn
    command: >-
      bash -c "python scripts/warmup_whisper.py && uvicorn server.app:create_app --factory --host 0.0.0.0 --port 3000"
    depends_on:
      - redis

  # The Redis service for state management and Celery message brokering
  redis:
    image: redis:7-alpine
    ports:
      # Expose Redis to the host for debugging, but services will connect internally
      - "6379:6379"

  # Celery worker handling background tasks
  celeryworker:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    command: celery -A server.celery_app worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  celerybeat:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    command: celery -A server.celery_app beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  # Grafana service for metrics dashboards
  grafana:
    image: grafana/grafana:9.5.3
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:

