site_name: TEL3SIS
nav:
  - Home: index.md
  - API Usage: api_usage.md
  - API Reference: api_reference.md
  - Grafana Dashboard: grafana.md
  - Backups: backups.md
  - User Guide: user_guide.md
  - Developer Guide: development.md
  - Reviews:
      - Build, Test & Deploy Review: reviews/build_test_deploy_review.md
      - Build, Test & Deployment Review: reviews/build_test_deployment_review.md
      - Interfaces & Interactions Review: reviews/interfaces_interactions_review.md
      - Core Logic Architecture Review: reviews/core_logic_architecture_review.md
      - Drift Analysis & Decision Audit: reviews/drift_analysis_report.md

