site_name: TEL3SIS
nav:
  - Home: index.md
  - API Usage: api_usage.md
  - Reviews:
      - Build, Test & Deploy Review: reviews/build_test_deploy_review.md
      - Interfaces & Interactions Review: reviews/interfaces_interactions_review.md
      - Core Logic Architecture Review: reviews/core_logic_architecture_review.md

