groups:
  - name: http
    rules:
      - alert: HighHttpErrorRate
        expr: sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "HTTP 5xx error rate above 5%"
          description: "More than 5% of HTTP requests returned errors in the last 5 minutes."
      - alert: HighHttpLatency
        expr: histogram_quantile(0.95, rate(http_request_latency_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "HTTP latency 95th percentile above 2s"
          description: "95th percentile HTTP request latency exceeded 2 seconds over the last 5 minutes."
