groups:
  - name: latency
    rules:
      - alert: HighSTTLatency
        expr: rate(stt_latency_seconds_sum[1m]) / rate(stt_latency_seconds_count[1m]) > 3
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "STT latency above 3s"
          description: "Average speech-to-text latency exceeded 3 seconds for over a minute."
      - alert: HighLLMLatency
        expr: rate(llm_latency_seconds_sum[1m]) / rate(llm_latency_seconds_count[1m]) > 3
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "LLM latency above 3s"
          description: "Average LLM response latency exceeded 3 seconds for over a minute."
      - alert: HighTTSLatency
        expr: rate(tts_latency_seconds_sum[1m]) / rate(tts_latency_seconds_count[1m]) > 3
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "TTS latency above 3s"
          description: "Average text-to-speech latency exceeded 3 seconds for over a minute."
