name: CoordinatorAgent Runner

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/create-github-app-token@v1
        id: app
        with:
          app-id: ${{ secrets.CA_APP_ID }}
          private-key: ${{ secrets.CA_APP_KEY }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements-dev.txt
      - name: Run CoordinatorAgent
        env:
          GITHUB_TOKEN: ${{ steps.app.outputs.token }}
        run: |
          python - <<'PY'
          from agents.coordinator import CoordinatorAgent
          import os
          from logging_config import configure_logging, logger

          configure_logging()
          agent = CoordinatorAgent(token=os.environ['GITHUB_TOKEN'])
          tasks = agent.load_tasks()
          logger.bind(count=len(tasks)).info("loaded_tasks")
          PY
